---
title: "Résumé"
---


# Professional Summary

Results-oriented marketing and analytics professional with a strong foundation in data analysis, digital strategy, and performance reporting. Skilled in leveraging analytics tools and programming languages to uncover insights and support decision-making across cross-functional teams.

# Technical Skills

- **Tools:** Qualtrics, Looker Studio, Tableau, Google Analytics 4, Google Tag Manager, Google Ads, ArcGIS, Monday.com 
- **Technical:** R, SQL, WordPress, HTML, CSS, WCAG
- **Methods:** Data Visualization, A/B Testing, Customer Segmentation, Market Research, Campaign Analysis, SEO Optimization, UX/UI Principles, Theme Analysis, Crosstab Analysis

# Education

| Degree           | Year | Institution |
|---|---|---|
| MS in Digital Marketing and Analytics | 2024–2026 | California State Polytechnic University, Pomona, CA |
| Bachelor of Business Administration (Honors), *Major in Marketing* | 2020–2024 | Ahmedabad University, Gujarat, India |

# Work Experience

### Data Analyst Assistant
<div style="display:flex; justify-content:space-between; align-items:center; margin-bottom:0.75rem;"><strong style="color:black;">Associated Student Inc. - Pomona, CA</strong><strong style="color:black;">Jun 2025 – Present</strong></div>

- Designed and deployed 6 cross-campus surveys using **Qualtrics** and **Excel**, achieved from 85% to 95% response rates and supporting data-driven decision-making across departments.
- Performed crosstab and segmented analysis on 450+ employees, identified key trends and delivering insights that improved engagement, with 79% reporting stronger connection to the organization.
- Led themes analysis of 400+ open-ended responses in **Dedoose**, to identify patterns in user behavior and translating findings into actionable recommendations across 10 teams.
- Collaborated with cross-functional teams to define research questions and success metrics and communicated insights through clear data storytelling to support decision-making.

---

### Web Assistant
<div style="display:flex; justify-content:space-between; align-items:center; margin-bottom:0.75rem;"><strong style="color:black;">Cal Poly Pomona Enterprises - Pomona, CA </strong><strong style="color:black;">Apr 2025 – Present</strong></div>

- Managed and developed website content using WordPress, HTML, and CSS, ensuring accuracy, accessibility, and alignment with brand and promotional standards
- Audited and resolved site issues, improving accessibility score from 7 to 9.7/10 and achieving full WCAG compliance pre-launch
- Analyzed 15+ university websites to identify navigation and content trends, translating findings into Figma wireframes and sitemaps
-Collaborated with designers, developers, and IT teams to execute site updates, campaign content, and QA for a successful website launch

---